CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 torchrun --nproc_per_node 7 src/train_bash.py \
    --stage dpo \
    --model_name_or_path outputs/baichuan-13b-sft \
    --lora_target W_pack \
    --template vicuna \
    --do_train \
    --do_eval \
    --dataset cvalues_comparison \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --optim adamw_hf \
    --output_dir outputs/baichuan-13b-dpo \
    --max_target_length 512 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --weight_decay 0.05 \
    --save_total_limit 3 \
    --logging_steps 10 \
    --save_steps 500 \
    --report_to none \
    --eval_steps 10 \
    --warmup_steps 100 \
    --dev_ratio 0.01 \
    --learning_rate 5e-4 \
    --max_grad_norm 10.0 \
    --num_train_epochs 1 \
    --resume_lora_training False \
    --remove_unused_columns False \
    --fp16 \
    --plot_loss