CUDA_VISIBLE_DEVICES=0,1,2,3,4 torchrun --nproc_per_node 5 src/train_bash.py \
    --stage rm \
    --model_name_or_path outputs/baichuan-7b-sft \
    --lora_target W_pack,o_proj,gate_proj,up_proj,down_proj \
    --template vicuna \
    --do_train \
    --dataset news_rm \
    --finetuning_type lora \
    --output_dir outputs/baichuan-7b-news-rm \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_total_limit 2\
    --save_steps 1000 \
    --eval_steps 1000 \
    --evaluation_strategy steps \
    --val_size 0.01 \
    --learning_rate 5e-5 \
    --num_train_epochs 1 \
    --resume_lora_training False \
    --overwrite_output_dir \
    --report_to none \
    --plot_loss \
    --fp16