CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 deepspeed src/train_bash.py \
    --stage sft \
    --deepspeed configs/ds_zero2.json \
    --lora_target q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj \
    --template vicuna \
    --model_name_or_path ../tigerbot-70b-base \
    --do_train \
    --dataset lawyer_llama_data,news_ext,cvalues_sft,belle_platypus_sharegpt4 \
    --max_samples 10000,10000,1000,100000 \
    --optim paged_adamw_32bit \
    --finetuning_type lora \
    --quantization_bit 4 \
    --lora_rank 64 \
    --lora_alpha 16 \
    --max_grad_norm 0.3 \
    --warmup_ratio 0.03 \
    --output_dir outputs/tigerbot-70b-sft-v2 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --preprocessing_num_workers 16 \
    --lr_scheduler_type cosine \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --logging_steps 1 \
    --save_steps 100 \
    --save_total_limit 3 \
    --learning_rate 2e-4 \
    --val_size 0.001 \
    --num_train_epochs 3 \
    --resume_lora_training True \
    --plot_loss \
    --report_to none \
    --fp16 \
    --tf32 True
