CUDA_VISIBLE_DEVICES=0,1,2,3,4 torchrun --nproc_per_node 5 src/train_bash.py \
    --stage dpo \
    --model_name_or_path outputs/chinese-llama-2-7b-sft \
    --lora_target q_proj,v_proj \
    --template vicuna \
    --padding_side right \
    --do_train \
    --do_eval \
    --dataset news_rm \
    --finetuning_type lora \
    --lora_rank 8 \
    --lora_alpha 32 \
    --optim adamw_hf \
    --output_dir outputs/chinese-llama-2-7b-news-dpo \
    --max_target_length 512 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 12 \
    --lr_scheduler_type cosine \
    --weight_decay 0.05 \
    --logging_steps 10 \
    --save_steps 1000 \
    --report_to none \
    --eval_steps 10 \
    --warmup_steps 100 \
    --val_size 0.01 \
    --learning_rate 1e-5 \
    --max_grad_norm 10.0 \
    --num_train_epochs 1 \
    --resume_lora_training False \
    --remove_unused_columns False \
    --fp16 \
    --plot_loss