CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 deepspeed src/train_bash.py \
    --stage ppo \
    --deepspeed configs/ds_zero2.json \
    --model_name_or_path outputs/baichuan2-llama-7b-sft \
    --lora_target q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj \
    --template vicuna \
    --do_train \
    --dataset hh_rlhf_cn_prompt \
    --top_k 0 \
    --top_p 0.9 \
    --do_sample \
    --ptx_coef 27.8 \
    --init_kl_coef 0.05 \
    --vf_coef 1 \
    --ppo_score_norm True \
    --finetuning_type lora \
    --reward_model outputs/baichuan2-llama-7b-rm \
    --output_dir outputs/baichuan2-7b-ppo \
    --overwrite_output_dir \
    --max_target_length 512 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --save_total_limit 3 \
    --logging_steps 1 \
    --save_steps 100 \
    --report_to none \
    --eval_steps 10 \
    --learning_rate 1e-5 \
    --actor_learning_rate 5e-4 \
    --critic_learning_rate 1e-5 \
    --num_train_epochs 1 \
    --resume_lora_training False \
    --fp16 \
    --plot_loss