CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 deepspeed --num_gpus=8 src/train_bash.py \
    --stage sft \
    --deepspeed configs/ds_zero3.json \
    --lora_target q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj \
    --template vicuna \
    --model_name_or_path ../Qwen-14B \
    --do_train \
    --dataset lawyer_llama_data,cvalues_sft,belle_platypus_sharegpt4,mathinstruct,evol_code_66k \
    --max_samples 10000,1000,70000,10000,10000 \
    --ptx_coef 0.75 \
    --finetuning_type full \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --warmup_ratio 0.03 \
    --optim adamw_torch \
    --output_dir outputs/qwen-14b-sft \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 12 \
    --lr_scheduler_type cosine \
    --evaluation_strategy epoch \
    --save_strategy steps \
    --max_source_length 1024 \
    --max_target_length 1024 \
    --eval_steps 100 \
    --logging_steps 1 \
    --save_steps 100 \
    --save_total_limit 3 \
    --learning_rate 5e-5 \
    --val_size 0.001 \
    --num_train_epochs 3 \
    --resume_lora_training False \
    --overwrite_output_dir \
    --plot_loss \
    --report_to none \
    --bf16 \
    --tf32 True
